### ISSUE TITLE
Cauldron result_menu doesn't update back to the main_menu after taking items out

### ISSUE THREAD

**Issue by AnatomyKing** [WolfyScript/CustomCrafting#348]
### What happened?

I was creating a custom Gui using font textures for the Cauldron since it's supports that. But after the Cauldron is done cooking, and you take your items out. the result_menu title doesn't update back to the main_menu title

https://github.com/WolfyScript/CustomCrafting/assets/128033443/f4cc0246-6280-4ae4-ad0f-72ea37b68401

### How can the bug be reproduced?

```yml
workstation:
  cauldron:
    interaction: NORMAL
    gui:
      main_menu:
        title: menu1
      result_menu:
        title: menu2
```
if you take the items out of the cauldron you will see that the items do update. But the menu title stays on `menu2`

### Expected Behaviour?

after you take your items out of the result_menu it suppose to not only update the items but also the menu title

### Plugin version

WolfyUtils v4.16.15-beta.11 & CustomCrafting v4.16.9-beta.7

### Server software

McPaper 1.20.4 Build 405

### Submit issue

- [X] read the Wiki and especially the FaQ, and made sure there is no fix to your issue,
- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).
