### ISSUE TITLE
compatibility Epic BackPacks plugin

### ISSUE THREAD

**Issue by MrJorman** [WolfyScript/CustomCrafting#95]
### The Problem

When I create a backpack that takes an item from the ItemsAdder register and place it in the CustomCrafting crafting slot, the NBT tags of the backpack are reset and taken from the ItemsAdder plugin and not from the EpicBackpacks plugin itself, and after that the backpack does not work.

```
 cool_backpack:
    display_name: '&fCool Backpack'
    item:
      type: ITEMSADDER_ITEM
      name: plastic_bag
    size: 3
```

### Solution

When I create a backpack that takes an item from the ItemsAdder register and place it in the CustomCrafting crafting slot, the NBT tags of the backpack are reset and taken from the ItemsAdder plugin and not from the EpicBackpacks plugin itself, and after that the backpack does not work.

```
 cool_backpack:
    display_name: '&fCool Backpack'
    item:
      type: ITEMSADDER_ITEM
      name: plastic_bag
    size: 3
```

### Alternatives

When I create a backpack that takes an item from the ItemsAdder register and place it in the CustomCrafting crafting slot, the NBT tags of the backpack are reset and taken from the ItemsAdder plugin and not from the EpicBackpacks plugin itself, and after that the backpack does not work.

```
 cool_backpack:
    display_name: '&fCool Backpack'
    item:
      type: ITEMSADDER_ITEM
      name: plastic_bag
    size: 3
```

### Additional Context

When I create a backpack that takes an item from the ItemsAdder register and place it in the CustomCrafting crafting slot, the NBT tags of the backpack are reset and taken from the ItemsAdder plugin and not from the EpicBackpacks plugin itself, and after that the backpack does not work.

```
 cool_backpack:
    display_name: '&fCool Backpack'
    item:
      type: ITEMSADDER_ITEM
      name: plastic_bag
    size: 3
```

### Submit issue

- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).
